const errorType = {
  404: "404",
  MISSING_RECORD: "MISSING_RECORD",
};

const errorMsg = {
  MISSING_TEACHER: "UNABLE TO FIND RECORD OF TEACHER!",
  MISSING_STUDENT: "ONE OR MORE STUDENTS DO NOT EXIST, PLEASE TRY AGAIN!",
  MISSING_ROUTE: "ROUTE NOT FOUND",
};

module.exports = {
  errorType,
  errorMsg,
};
